spring:
 datasource:
   username: sa
   password:
   url: jdbc:h2:file:C:/data/sample
   driver-class-name: org.h2.Driver
h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
 jpa:
   hibernate:
     ddl-auto: create-drop
